spring:
  application:
    name: ServiceRegistry

eureka:
  instance:
    hostname: eureka-server
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
      
management:
  tracing:
    sampling:
      probability: 1.0
server:
  port: 8761
